### ISSUE TITLE
API endpoint for getting products

### ISSUE THREAD

**Issue by FaizanPotrick** [SnehaDeshmukh28/API-Hacktoberfest#1]
Method: GET
Make an API call to 

1) Route: /products/categories/:category (get a list of all products in the specified category)
2) Route: /products/search?title=${Product}
3) Route: /products/price-range (use a query string to get minPrice and maxPrice)

**Comment by FaizanPotrick** [comment]
can you assign me

**Comment by SnehaDeshmukh28** [comment]
Sure. Go Ahead!!
